# Setup
title:               bmacho's guitar-tabs
description:         ''

github.repo:		 https://github.com/bmacho/lanyon/

permalink: /:path

include: [_pages/, _pages, _tabs, _tabs/]
exclude: [_tabs/sample.html, Gemfile, Gemfile.lock, gems, node_modules, vendor, LICENSE.md, README.md, _posts/]

collections:
  tabs:
    output: true

emptyArray: []
