# Setup
title:               bmacho's guitar-tabs
description:         ''

github.repo:		 https://github.com/bmacho/lanyon/

permalink: /:path

include: [ _pages, _tabs ]
exclude: [ _posts, _tabs/sample.html, drafts, _tabs/drafts/, Gemfile, Gemfile.lock, gems, node_modules, vendor, LICENSE.md, README.md ]

collections:
  tabs:
    output: true
    permalink: /:collection/:name

emptyArray: []
